version: '3.3'
services:
  jekyll:
    command: ["jekyll", "serve", "--drafts", "--incremental", "--watch"]
    image: jekyll/jekyll:latest
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
